# Generated by Django 3.0.2 on 2020-09-18 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('city', models.CharField(default='تهران', max_length=30, verbose_name='شهر')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='تلفن')),
                ('address', models.TextField(verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'سینما',
                'verbose_name_plural': 'سینما',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان فیلم')),
                ('director', models.CharField(max_length=50, verbose_name='نام کارگردان')),
                ('year', models.IntegerField(verbose_name='سال تولید')),
                ('length', models.IntegerField(verbose_name='مدت زمان')),
                ('description', models.TextField(verbose_name='خلاصه فیلم')),
            ],
            options={
                'verbose_name': 'فیلم',
                'verbose_name_plural': 'فیلم',
            },
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='زمان شروع')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('salable_seats', models.IntegerField(verbose_name='صندلی\u200cهای قابل فروش')),
                ('free_seats', models.IntegerField(verbose_name='صندلی\u200cهای خالی')),
                ('status', models.IntegerField(choices=[(1, 'فروش آغاز نشده'), (2, 'در حال فروش بلیط'), (3, 'بلیط\u200cهای تمام شد'), (4, 'فروش بلیط بسته\u200cشد'), (5, 'فیلم پخش شد'), (6, 'سانس لغو شد')], verbose_name='وضعیت')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.Cinema', verbose_name='نام سینما')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.Movie', verbose_name='عنوان فیلم')),
            ],
            options={
                'verbose_name': 'سانس',
                'verbose_name_plural': 'سانس',
            },
        ),
    ]
