# Generated by Django 3.0.2 on 2020-09-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showtime',
            options={},
        ),
    ]
