# Generated by Django 3.0.2 on 2020-09-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_auto_20200922_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showtime',
            options={'verbose_name': 'سانس', 'verbose_name_plural': 'سانس'},
        ),
    ]
