# Generated by Django 3.0.2 on 2020-09-21 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'نمایه کاربری', 'verbose_name_plural': 'نمایه کاربری'},
        ),
    ]
